- include: java7.yml

- name: create clojure directory
  command: mkdir -p /opt/clojure
    creates=/opt/clojure

- name: get clojure jars
  command: wget -O /opt/clojure/clojure-1.6.0.jar http://central.maven.org/maven2/org/clojure/clojure/1.6.0/clojure-1.6.0.jar 
    creates=/opt/clojure/clojure-1.6.0.jar

- name: install clojure runner
  copy: source=templates/clj-run dest=/usr/local/bin mode=775
